SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

SCALE_FACTOR = 1.5

ASTEROID_MIN_RADIUS = 15 * SCALE_FACTOR
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.7
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = int(15 * SCALE_FACTOR)
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
PLAYER_SHOOT_SPEED = 500
PLAYER_FIRE_COOLDOWN = 0.2
PLAYER_LIVES = 3
PLAYER_IFRAMES = 180

SHOT_RADIUS = 5
